WIP: Port to NuttX
RodrigoDornelles/3bc-lang pull request #249
Opened 2022-01-08 19:03 UTC by microhobby

Let's port the awesome 3BC to NuttX

2022-01-21 23:38 UTC, microhobby commented
@RodrigoDornelles I think this is good to review, please let me know about the documentation if you think that is best also add on this pull request.

2022-01-22 19:14 UTC, RodrigoDornelles requested changes
There are a few small changes that can be made, as soon as I can compile for nuttx, I will help resolve these requests.

2022-01-22 19:14 UTC, RodrigoDornelles commented on src/3bc_macros.h
> +#if defined(__nuttx__)
Is there any other compilation constants besides the one defined by the programmer? (such as from the nuttx kernel itself)

2022-01-22 19:14 UTC, RodrigoDornelles commented on src/3bc_optional_interpreter.h
> +#ifdef __nuttx__
use constant _3BC_NUTTX

2022-01-22 19:14 UTC, RodrigoDornelles commented on src/3bc_optional_interpreter.h
> +#ifdef __nuttx__
use constant _3BC_NUTTX

2022-01-22 19:14 UTC, RodrigoDornelles commented on src/3bc_optional_interpreter.h
> +#ifdef __nuttx__
could be that when not REPL, still print source code, this behavior is not expected.

2022-01-22 19:14 UTC, RodrigoDornelles commented on src/driver_tty.c
> +        fflush(tty.io.stream);
This may cause unexpected behavior, it may not be necessary.

2022-05-09 15:14 UTC, RodrigoDornelles approved these changes

2022-05-27 18:24 UTC, merged