For - While Loop refactored
RodrigoDornelles/3bc-lang pull request #367
Opened 2022-10-18 04:46 UTC by Yugal41735

# Description

For-while loop refactored as mentioned in issue=> #344 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2022-10-18 12:00 UTC, RodrigoDornelles requested changes
There are some changes to be made!

please I just discovered yesterday that `++i` has a performance gain in 6502 family, would like to see this in the same PR.

ref: https://cc65.github.io/doc/coding.html item 9

2022-10-18 12:00 UTC, RodrigoDornelles commented on src/ds_label_hash.c
> +        last_node = last_node->next;
to maintain the same behavior change to:
```c
while (last_node->next != NULL) {
      last_node = last_node->next;
 }
 ```

2022-10-18 15:46 UTC, Yugal41735 commented
Done, the necessary changes. You could review it again.

2022-10-18 15:47 UTC, Yugal41735 commented
Done, the necessary changes. You could review it again.  @RodrigoDornelles

2022-10-18 16:31 UTC, RodrigoDornelles approved these changes

2022-10-18 16:41 UTC, RodrigoDornelles requested changes

2022-10-18 16:41 UTC, RodrigoDornelles commented on src/driver_custom.c
> +            ++last_func;
### error occurred ###
```
In file included from programs/../src/3bc.h:133,
                 from programs/tests.c:2:
programs/../src/driver_custom.c: In function ‘void driver_custom_set(app_3bc_s*, cpumode_3bc_t, register_3bc_t, function_3bc_t)’:
programs/../src/driver_custom.c:6[8](https://github.com/RodrigoDornelles/3bc-lang/actions/runs/3274913903/jobs/5389836982#step:3:9):2[9](https://github.com/RodrigoDornelles/3bc-lang/actions/runs/3274913903/jobs/5389836982#step:3:10): error: ‘actual_func’ was not declared in this scope; did you mean ‘atual_func’?
   68 |         while (last_func <= actual_func)
      |                             ^~~~~~~~~~~
      |                             atual_func
make: *** [Makefile:86: tests-full] Error 1
Error: Process completed with exit code 2.
```

### to solve ###

its my typo wrong, but the **actual** term is still not so correct, replace the `actual_func` and `current_func` in place use `current_func`

2022-10-18 16:41 UTC, RodrigoDornelles commented on src/interpreter_tokens.c
> +        while (strchr("\t. ", *pointer) != NULL && pointer[0] != '\0'){
format: `while (strchr("\t. ", *pointer) != NULL && pointer[0] != '\0') {`

2022-10-18 16:41 UTC, RodrigoDornelles commented on src/interpreter_tokens.c
> +            while (pointer[0] != '\n' && pointer[0] != '\0' && pointer[0] != EOF){
format: `while (pointer[0] != '\n' && pointer[0] != '\0' && pointer[0] != EOF) {`

2022-10-18 16:41 UTC, RodrigoDornelles commented on src/driver_custom.c
> +            ++last_func;
don't forget to take care of the indentation, you can use clang-format to check.

2022-10-18 16:41 UTC, RodrigoDornelles commented on src/ds_label_hash.c
> +    while ( last_node->next != NULL) {
format: `while (last_node->next != NULL) {`

2022-10-18 18:58 UTC, RodrigoDornelles requested changes

2022-10-18 18:58 UTC, RodrigoDornelles commented on src/interpreter_tokens.c
> +
problem is it must be within the 80 characters of column.
```c
            while (
                pointer[0] != '\n' && pointer[0] != '\0' && pointer[0] != EOF) {
                ++pointer;
            }

            break;
        }
```

2022-10-18 22:23 UTC, RodrigoDornelles commented
it's been so long since the indentation errors, you can try again, but if it doesn't work I'll close the pullrequest without the merge. @Yugal41735

2022-10-18 23:29 UTC, Yugal41735 commented
I will try again and let you know.

On Wed, 19 Oct 2022, 03:53 RodrigoDornelles, ***@***.***>
wrote:

> it's been so long since the indentation errors, you can try again, but if
> it doesn't work I'll close the pullrequest without the merge. @Yugal41735
> <https://github.com/Yugal41735>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RodrigoDornelles/3bc-lang/pull/367#issuecomment-1283076187>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARZOLN7Q7FNVBLLVHPAAYDLWD4PNLANCNFSM6AAAAAARHV2MUM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-19 11:39 UTC, Yugal41735 commented
If this does not work, I could try again, and do you know of any online tool, for checking clang-format, bcz due to some internal errors, I am having difficulty in checking clang-format locally.

2022-10-19 16:32 UTC, RodrigoDornelles approved these changes

2022-10-19 16:33 UTC, merged